type IcaoNationalityMark = {
  codes: string[];
  en: string;
  ru: string;
  kk: string;
  ja: string;
};

export type GeoStatus = "off" | "searching" | "fixed";

export const ICAO_NATIONALITY_MARKS: IcaoNationalityMark[] = [
  { codes: [ '14', '15', 'RA', 'UU', 'UL', 'UW', 'UR', 'UE', 'UF', 'UH', 'UI'], en: 'Russia', ru: 'Россия', kk: 'Ресей', ja: 'ロシア' },
  { codes: ['YA', 'A4'], en: 'Afghanistan', ru: 'Афганистан', kk: 'Ауғанстан', ja: 'アフガニスタン' },
  { codes: ['ZA'], en: 'Albania', ru: 'Албания', kk: 'Албания', ja: 'アルバニア' },
  { codes: ['7T'], en: 'Algeria', ru: 'Алжир', kk: 'Алжир', ja: 'アルジェリア' },
  { codes: ['D2'], en: 'Angola', ru: 'Ангола', kk: 'Ангола', ja: 'アンゴラ' },
  {
    codes: ['V2'],
    en: 'Antigua and Barbuda',
    ru: 'Антигуа и Барбуда',
    kk: 'Антигуа және Барбуда',
    ja: 'アンティグア・バーブーダ',
  },
  { codes: ['LQ', 'LV'], en: 'Argentina', ru: 'Аргентина', kk: 'Аргентина', ja: 'アルゼンチン' },
  { codes: ['EK'], en: 'Armenia', ru: 'Армения', kk: 'Әрмения', ja: 'アルメニア' },
  { codes: ['VH', 'Y'], en: 'Australia', ru: 'Австралия', kk: 'Австралия', ja: 'オーストラリア' },
  { codes: ['OE', 'V'], en: 'Austria', ru: 'Австрия', kk: 'Австрия', ja: 'オーストリア' },
  { codes: ['4K'], en: 'Azerbaijan', ru: 'Азербайджан', kk: 'Әзербайжан', ja: 'アゼルバイジャン' },
  { codes: ['C6'], en: 'Bahamas', ru: 'Багамы', kk: 'Багам аралдары', ja: 'バハマ' },
  { codes: ['A9C'], en: 'Bahrain', ru: 'Бахрейн', kk: 'Бахрейн', ja: 'バーレーン' },
  { codes: ['S2'], en: 'Bangladesh', ru: 'Бангладеш', kk: 'Бангладеш', ja: 'バングラデシュ' },
  { codes: ['8P'], en: 'Barbados', ru: 'Барбадос', kk: 'Барбадос', ja: 'バルバドス' },
  { codes: ['EW'], en: 'Belarus', ru: 'Беларусь', kk: 'Беларусь', ja: 'ベラルーシ' },
  { codes: ['OO'], en: 'Belgium', ru: 'Бельгия', kk: 'Бельгия', ja: 'ベルギー' },
  { codes: ['V3'], en: 'Belize', ru: 'Белиз', kk: 'Белиз', ja: 'ベリーズ' },
  { codes: ['TY'], en: 'Benin', ru: 'Бенин', kk: 'Бенин', ja: 'ベナン' },
  { codes: ['A5', 'A3'], en: 'Bhutan', ru: 'Бутан', kk: 'Бутан', ja: 'ブータン' },
  { codes: ['CP'], en: 'Bolivia', ru: 'Боливия', kk: 'Боливия', ja: 'ボリビア' },
  {
    codes: ['E7'],
    en: 'Bosnia and Herzegovina',
    ru: 'Босния и Герцеговина',
    kk: 'Босния және Герцеговина',
    ja: 'ボスニア・ヘルツェゴビナ',
  },
  { codes: ['A2'], en: 'Botswana', ru: 'Ботсвана', kk: 'Ботсвана', ja: 'ボツワナ' },
  { codes: ['PP', 'PR', 'PS', 'PT', 'PU'], en: 'Brazil', ru: 'Бразилия', kk: 'Бразилия', ja: 'ブラジル' },
  {
    codes: ['V8'],
    en: 'Brunei Darussalam',
    ru: 'Бруней-Даруссалам',
    kk: 'Бруней-Даруссалам',
    ja: 'ブルネイ・ダルサラーム',
  },
  { codes: ['LZ'], en: 'Bulgaria', ru: 'Болгария', kk: 'Болгария', ja: 'ブルガリア' },
  { codes: ['XT'], en: 'Burkina Faso', ru: 'Буркина-Фасо', kk: 'Буркина-Фасо', ja: 'ブルキナファソ' },
  { codes: ['9U'], en: 'Burundi', ru: 'Бурунди', kk: 'Бурунди', ja: 'ブルンジ' },
  { codes: ['D4'], en: 'Cabo Verde', ru: 'Кабо-Верде', kk: 'Кабо-Верде', ja: 'カーボベルデ' },
  { codes: ['XU'], en: 'Cambodia', ru: 'Камбоджа', kk: 'Камбоджа', ja: 'カンボジア' },
  { codes: ['TJ'], en: 'Cameroon', ru: 'Камерун', kk: 'Камерун', ja: 'カメルーン' },
  { codes: ['C', 'CF', 'TC'], en: 'Canada', ru: 'Канада', kk: 'Канада', ja: 'カナダ' },
  {
    codes: ['TL'],
    en: 'Central African Republic',
    ru: 'Центральноафриканская Республика',
    kk: 'Орталық Африка Республикасы',
    ja: '中央アフリカ共和国',
  },
  { codes: ['TT'], en: 'Chad', ru: 'Чад', kk: 'Чад', ja: 'チャド' },
  { codes: ['CC'], en: 'Chile', ru: 'Чили', kk: 'Чили', ja: 'チリ' },
  { codes: ['B', 'ZW', 'ZY'], en: 'China', ru: 'Китай', kk: 'Қытай', ja: '中国' },
  { codes: ['HJ', 'HK'], en: 'Colombia', ru: 'Колумбия', kk: 'Колумбия', ja: 'コロンビア' },
  { codes: ['D6'], en: 'Comoros', ru: 'Коморы', kk: 'Комор аралдары', ja: 'コモロ' },
  { codes: ['TN'], en: 'Congo', ru: 'Конго', kk: 'Конго', ja: 'コンゴ共和国' },
  { codes: ['E5'], en: 'Cook Islands', ru: 'Острова Кука', kk: 'Кук аралдары', ja: 'クック諸島' },
  { codes: ['TI'], en: 'Costa Rica', ru: 'Коста-Рика', kk: 'Коста-Рика', ja: 'コスタリカ' },
  { codes: ['TU'], en: 'Côte d’Ivoire', ru: 'Кот-д’Ивуар', kk: 'Кот-д’Ивуар', ja: 'コートジボワール' },
  { codes: ['9A'], en: 'Croatia', ru: 'Хорватия', kk: 'Хорватия', ja: 'クロアチア' },
  { codes: ['CU'], en: 'Cuba', ru: 'Куба', kk: 'Куба', ja: 'キューバ' },
  { codes: ['5B'], en: 'Cyprus', ru: 'Кипр', kk: 'Кипр', ja: 'キプロス' },
  { codes: ['OK'], en: 'Czechia', ru: 'Чехия', kk: 'Чехия', ja: 'チェコ' },
  { codes: ['P', 'P5'], en: 'North Korea', ru: 'Северная Корея', kk: 'Солтүстік Корея', ja: '北朝鮮' },
  {
    codes: ['9Q'],
    en: 'Democratic Republic of the Congo',
    ru: 'Демократическая Республика Конго',
    kk: 'Конго Демократиялық Республикасы',
    ja: 'コンゴ民主共和国',
  },
  { codes: ['OY'], en: 'Denmark', ru: 'Дания', kk: 'Дания', ja: 'デンマーク' },
  { codes: ['J2'], en: 'Djibouti', ru: 'Джибути', kk: 'Джибути', ja: 'ジブチ' },
  { codes: ['J7'], en: 'Dominica', ru: 'Доминика', kk: 'Доминика', ja: 'ドミニカ国' },
  {
    codes: ['HI'],
    en: 'Dominican Republic',
    ru: 'Доминиканская Республика',
    kk: 'Доминикан Республикасы',
    ja: 'ドミニカ共和国',
  },
  { codes: ['HC'], en: 'Ecuador', ru: 'Эквадор', kk: 'Эквадор', ja: 'エクアドル' },
  { codes: ['SU'], en: 'Egypt', ru: 'Египет', kk: 'Мысыр', ja: 'エジプト' },
  { codes: ['YS'], en: 'El Salvador', ru: 'Сальвадор', kk: 'Эль-Сальвадор', ja: 'エルサルバドル' },
  { codes: ['3C'], en: 'Equatorial Guinea', ru: 'Экваториальная Гвинея', kk: 'Экваториалды Гвинея', ja: '赤道ギニア' },
  { codes: ['E3'], en: 'Eritrea', ru: 'Эритрея', kk: 'Эритрея', ja: 'エリトリア' },
  { codes: ['ES'], en: 'Estonia', ru: 'Эстония', kk: 'Эстония', ja: 'エストニア' },
  { codes: ['3DC'], en: 'Eswatini', ru: 'Эсватини', kk: 'Эсватини', ja: 'エスワティニ' },
  { codes: ['ET'], en: 'Ethiopia', ru: 'Эфиопия', kk: 'Эфиопия', ja: 'エチオピア' },
  { codes: ['DQ'], en: 'Fiji', ru: 'Фиджи', kk: 'Фиджи', ja: 'フィジー' },
  { codes: ['OH'], en: 'Finland', ru: 'Финляндия', kk: 'Финляндия', ja: 'フィンランド' },
  { codes: ['F'], en: 'France', ru: 'Франция', kk: 'Франция', ja: 'フランス' },
  { codes: ['TR'], en: 'Gabon', ru: 'Габон', kk: 'Габон', ja: 'ガボン' },
  { codes: ['C5'], en: 'Gambia', ru: 'Гамбия', kk: 'Гамбия', ja: 'ガンビア' },
  { codes: ['4L'], en: 'Georgia', ru: 'Грузия', kk: 'Грузия', ja: 'ジョージア' },
  { codes: ['D'], en: 'Germany', ru: 'Германия', kk: 'Германия', ja: 'ドイツ' },
  { codes: ['9G', '9GR'], en: 'Ghana', ru: 'Гана', kk: 'Гана', ja: 'ガーナ' },
  { codes: ['SX'], en: 'Greece', ru: 'Греция', kk: 'Греция', ja: 'ギリシャ' },
  { codes: ['J3'], en: 'Grenada', ru: 'Гренада', kk: 'Гренада', ja: 'グレナダ' },
  { codes: ['TG'], en: 'Guatemala', ru: 'Гватемала', kk: 'Гватемала', ja: 'グアテマラ' },
  { codes: ['3X'], en: 'Guinea', ru: 'Гвинея', kk: 'Гвинея', ja: 'ギニア' },
  { codes: ['J5'], en: 'Guinea-Bissau', ru: 'Гвинея-Бисау', kk: 'Гвинея-Бисау', ja: 'ギニアビサウ' },
  { codes: ['8R'], en: 'Guyana', ru: 'Гайана', kk: 'Гайана', ja: 'ガイアナ' },
  { codes: ['HH'], en: 'Haiti', ru: 'Гаити', kk: 'Гаити', ja: 'ハイチ' },
  { codes: ['HR'], en: 'Honduras', ru: 'Гондурас', kk: 'Гондурас', ja: 'ホンジュラス' },
  { codes: ['HA', 'T'], en: 'Hungary', ru: 'Венгрия', kk: 'Венгрия', ja: 'ハンガリー' },
  { codes: ['TF'], en: 'Iceland', ru: 'Исландия', kk: 'Исландия', ja: 'アイスランド' },
  { codes: ['VT', 'VI'], en: 'India', ru: 'Индия', kk: 'Үндістан', ja: 'インド' },
  { codes: ['PK'], en: 'Indonesia', ru: 'Индонезия', kk: 'Индонезия', ja: 'インドネシア' },
  { codes: ['EP'], en: 'Iran', ru: 'Иран', kk: 'Иран', ja: 'イラン' },
  { codes: ['YI'], en: 'Iraq', ru: 'Ирак', kk: 'Ирак', ja: 'イラク' },
  { codes: ['EI', 'EJ'], en: 'Ireland', ru: 'Ирландия', kk: 'Ирландия', ja: 'アイルランド' },
  { codes: ['4X', '4Z'], en: 'Israel', ru: 'Израиль', kk: 'Израиль', ja: 'イスラエル' },
  { codes: ['I'], en: 'Italy', ru: 'Италия', kk: 'Италия', ja: 'イタリア' },
  { codes: ['6Y'], en: 'Jamaica', ru: 'Ямайка', kk: 'Ямайка', ja: 'ジャマイカ' },
  { codes: ['JA', 'J'], en: 'Japan', ru: 'Япония', kk: 'Жапония', ja: '日本' },
  { codes: ['JY'], en: 'Jordan', ru: 'Иордания', kk: 'Иордания', ja: 'ヨルダン' },
  { codes: ['UP'], en: 'Kazakhstan', ru: 'Казахстан', kk: 'Қазақстан', ja: 'カザフスタン' },
  { codes: ['5Y'], en: 'Kenya', ru: 'Кения', kk: 'Кения', ja: 'ケニア' },
  { codes: ['9K'], en: 'Kuwait', ru: 'Кувейт', kk: 'Кувейт', ja: 'クウェート' },
  { codes: ['EX'], en: 'Kyrgyzstan', ru: 'Киргизия', kk: 'Қырғызстан', ja: 'キルギス' },
  { codes: ['RDPL', 'VU'], en: 'Laos', ru: 'Лаос', kk: 'Лаос', ja: 'ラオス' },
  { codes: ['YL'], en: 'Latvia', ru: 'Латвия', kk: 'Латвия', ja: 'ラトビア' },
  { codes: ['OD'], en: 'Lebanon', ru: 'Ливан', kk: 'Ливан', ja: 'レバノン' },
  { codes: ['7P'], en: 'Lesotho', ru: 'Лесото', kk: 'Лесото', ja: 'レソト' },
  { codes: ['A8'], en: 'Liberia', ru: 'Либерия', kk: 'Либерия', ja: 'リベリア' },
  { codes: ['5A'], en: 'Libya', ru: 'Ливия', kk: 'Ливия', ja: 'リビア' },
  {
    codes: ['HB', 'H'],
    en: 'Liechtenstein / Switzerland',
    ru: 'Лихтенштейн / Швейцария',
    kk: 'Лихтенштейн / Швейцария',
    ja: 'リヒテンシュタイン / スイス',
  },
  { codes: ['LY'], en: 'Lithuania', ru: 'Литва', kk: 'Литва', ja: 'リトアニア' },
  { codes: ['LX'], en: 'Luxembourg', ru: 'Люксембург', kk: 'Люксембург', ja: 'ルクセンブルク' },
  { codes: ['5R'], en: 'Madagascar', ru: 'Мадагаскар', kk: 'Мадагаскар', ja: 'マダガスカル' },
  { codes: ['7Q'], en: 'Malawi', ru: 'Малави', kk: 'Малави', ja: 'マラウイ' },
  { codes: ['9M'], en: 'Malaysia', ru: 'Малайзия', kk: 'Малайзия', ja: 'マレーシア' },
  { codes: ['1C'], en: 'Maldives', ru: 'Мальдивы', kk: 'Мальдив аралдары', ja: 'モルディブ' },
  { codes: ['ML'], en: 'Mali', ru: 'Мали', kk: 'Мали', ja: 'マリ' },
  { codes: ['MF'], en: 'Malta', ru: 'Мальта', kk: 'Мальта', ja: 'マルタ' },
  { codes: ['5T'], en: 'Mauritania', ru: 'Мавритания', kk: 'Мавритания', ja: 'モーリタニア' },
  { codes: ['3B'], en: 'Mauritius', ru: 'Маврикий', kk: 'Маврикий', ja: 'モーリシャス' },
  {
    codes: ['XA', 'XB', 'XC', 'XD', 'XE', 'XF', 'XG', 'XH', 'XI', 'XJ'],
    en: 'Mexico',
    ru: 'Мексика',
    kk: 'Мексика',
    ja: 'メキシコ',
  },
];

export const ThemeDark = {
    "theme": "modern",
    "icons": "lucide",
    "cssVars": {
    "light": {
      "--ml-ctrl-border-radius": "1rem",
        "--ml-font": "16px/24px system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, \"Open Sans\", \"Helvetica Neue\", sans-serif",
        "--ml-font-attribution": "inherit",
        "--ml-c-bg-1": "#ffffff",
        "--ml-c-bg-2": "#f0f0f0",
        "--ml-c-bg-3": "#d7d7d7",
        "--ml-c-icon-1": "#333333",
        "--ml-c-icon-2": "#000000",
        "--ml-c-active": "#1da1f2",
        "--ml-c-error": "#e54e33",
        "--ml-c-outline": "#dba726",
        "--ml-o-disabled": "0.25",
        "--ml-shadow": "0 1px 3px 0 rgb(0 0 0 / 0.15), 0 1px 2px -1px rgb(0 0 0 / 0.15)",
        "--ml-shadow-active": "0 10px 15px -3px rgb(0 0 0 / 0.15), 0 4px 6px -2px rgb(0 0 0 / 0.15)",
        "--ml-c-link-1": "#333333",
        "--ml-c-link-2": "#000000",
        "--ml-c-logo-1": "#ffffff",
        "--ml-c-logo-2": "#d7d7d7",
        "--ml-c-geoloc": "#1da1f2"
    },
    "dark": {
      "--ml-c-bg-1": "#111725",
        "--ml-c-bg-2": "#414853",
        "--ml-c-bg-3": "#32363f",
        "--ml-c-icon-1": "#cbd5e1",
        "--ml-c-icon-2": "#ffffff",
        "--ml-shadow": "0 1px 3px 0 rgb(0 0 0 / 0.15), 0 1px 2px -1px rgb(0 0 0 / 0.15)",
        "--ml-c-link-1": "#cbd5e1",
        "--ml-c-link-2": "#ffffff",
        "--ml-c-logo-1": "#111725",
        "--ml-c-logo-2": "#32363f"
    }
  }
}