export const ICAO_NATIONALITY_MARKS: Record<string, string> = {
  YA: 'Afghanistan',
  ZA: 'Albania',
  '7T': 'Algeria',
  D2: 'Angola',
  V2: 'Antigua and Barbuda',
  LQ: 'Argentina',
  LV: 'Argentina',
  EK: 'Armenia',
  VH: 'Australia',
  OE: 'Austria',
  '4K': 'Azerbaijan',
  C6: 'Bahamas',
  A9C: 'Bahrain',
  S2: 'Bangladesh',
  '8P': 'Barbados',
  EW: 'Belarus',
  OO: 'Belgium',
  V3: 'Belize',
  TY: 'Benin',
  A5: 'Bhutan',
  CP: 'Bolivia (Plurinational State of)',
  E7: 'Bosnia and Herzegovina',
  A2: 'Botswana',
  PP: 'Brazil',
  PR: 'Brazil',
  PS: 'Brazil',
  PT: 'Brazil',
  PU: 'Brazil',
  V8: 'Brunei Darussalam',
  LZ: 'Bulgaria',
  XT: 'Burkina Faso',
  '9U': 'Burundi',
  D4: 'Cabo Verde',
  XU: 'Cambodia',
  TJ: 'Cameroon',
  C: 'Canada',
  CF: 'Canada',
  TL: 'Central African Republic',
  TT: 'Chad',
  CC: 'Chile',
  B: 'China (including Hong Kong SAR and Macao SAR)',
  HJ: 'Colombia',
  HK: 'Colombia',
  D6: 'Comoros',
  TN: 'Congo',
  E5: 'Cook Islands',
  TI: 'Costa Rica',
  TU: 'Côte d’Ivoire',
  '9A': 'Croatia',
  CU: 'Cuba',
  '5B': 'Cyprus',
  OK: 'Czechia',
  P: 'Democratic People’s Republic of Korea*',
  '9Q': 'Democratic Republic of the Congo',
  OY: 'Denmark',
  J2: 'Djibouti',
  J7: 'Dominica',
  HI: 'Dominican Republic',
  HC: 'Ecuador',
  SU: 'Egypt',
  YS: 'El Salvador',
  '3C': 'Equatorial Guinea',
  E3: 'Eritrea',
  ES: 'Estonia',
  '3DC': 'Eswatini',
  ET: 'Ethiopia',
  DQ: 'Fiji',
  OH: 'Finland',
  F: 'France',
  TR: 'Gabon',
  C5: 'Gambia',
  '4L': 'Georgia',
  D: 'Germany',
  '9G': 'Ghana',
  '9GR': 'Ghana',
  SX: 'Greece',
  J3: 'Grenada',
  TG: 'Guatemala',
  '3X': 'Guinea',
  J5: 'Guinea-Bissau',
  '8R': 'Guyana',
  HH: 'Haiti',
  HR: 'Honduras',
  HA: 'Hungary',
  TF: 'Iceland',
  VT: 'India',
  PK: 'Indonesia',
  EP: 'Iran (Islamic Republic)',
  YI: 'Iraq',
  EI: 'Ireland',
  EJ: 'Ireland',
  '4X': 'Israel',
  '4Z': 'Israel',
  I: 'Italy',
  '6Y': 'Jamaica',
  JA: 'Japan',
  JY: 'Jordan',
  UP: 'Kazakhstan',
  '5Y': 'Kenya',
  '9K': 'Kuwait',
  EX: 'Kyrgyzstan',
  RDPL: 'Lao People’s Democratic Republic*',
  YL: 'Latvia',
  OD: 'Lebanon',
  '7P': 'Lesotho',
  A8: 'Liberia',
  '5A': 'Libya',
  HB: 'Liechtenstein / Switzerland (plus national emblem)',
  LY: 'Lithuania',
  LX: 'Luxembourg',
  '5R': 'Madagascar',
  '7Q': 'Malawi',
  '9M': 'Malaysia',
  '8Q': 'Maldives',
  TZ: 'Mali',
  '9H': 'Malta',
  V7: 'Marshall Islands',
  '5T': 'Mauritania',
  '3B': 'Mauritius',
  XA: 'Mexico',
  XB: 'Mexico',
  XC: 'Mexico',
  V6: 'Micronesia (Federated States of)',
  '3A': 'Monaco',
  JU: 'Mongolia',
  '4O': 'Montenegro',
  CN: 'Morocco',
  C9: 'Mozambique',
  XY: 'Myanmar',
  XZ: 'Myanmar',
  V5: 'Namibia',
  C2: 'Nauru',
  '9N': 'Nepal',
  PH: 'Netherlands',
  P4: 'Aruba',
  PJ: 'Curaçao / Sint Maarten',
  ZK: 'New Zealand',
  ZL: 'New Zealand',
  ZM: 'New Zealand',
  YN: 'Nicaragua',
  '5U': 'Niger',
  '5N': 'Nigeria',
  Z3: 'North Macedonia',
  LN: 'Norway',
  A4O: 'Oman',
  AP: 'Pakistan',
  T8: 'Palau',
  HP: 'Panama',
  P2: 'Papua New Guinea',
  ZP: 'Paraguay',
  OB: 'Peru',
  RP: 'Philippines*',
  CR: 'Portugal',
  CS: 'Portugal',
  A7: 'Qatar',
  HL: 'Republic of Korea',
  ER: 'Republic of Moldova',
  YR: 'Romania',
  RA: 'Russian Federation',
  '9XR': 'Rwanda',
  V4: 'Saint Kitts and Nevis',
  J6: 'Saint Lucia',
  J8: 'Saint Vincent and the Grenadines',
  '5W': 'Samoa',
  T7: 'San Marino',
  S9: 'Sao Tome and Principe',
  HZ: 'Saudi Arabia',
  '6V': 'Senegal',
  '6W': 'Senegal',
  YU: 'Serbia',
  S7: 'Seychelles',
  '9L': 'Sierra Leone',
  '9V': 'Singapore',
  OM: 'Slovakia',
  S5: 'Slovenia',
  H4: 'Solomon Islands',
  '6O': 'Somalia',
  ZS: 'South Africa',
  ZT: 'South Africa',
  ZU: 'South Africa',
  Z8: 'South Sudan',
  EC: 'Spain',
  '4R': 'Sri Lanka',
  ST: 'Sudan',
  PZ: 'Suriname',
  SE: 'Sweden',
  G: 'United Kingdom',
  'VP-A': 'Anguilla (UK)',
  'VP-B': 'Bermuda (UK)',
  'VQ-B': 'Bermuda (UK)',
  'VP-C': 'Cayman Islands (UK)',
  'VQ-C': 'Cayman Islands (UK)',
  'VP-F': 'Falkland Islands (Malvinas) (UK)',
  'VP-G': 'Gibraltar (UK)',
  M: 'Isle of Man (UK)',
  ZJ: 'Jersey (UK)',
  'VP-M': 'Montserrat (UK)',
  'VQ-H': 'St. Helena/Ascension (UK)',
  'VQ-T': 'Turks and Caicos (UK)',
  'VP-L': 'Virgin Islands (UK)',
  '5H': 'United Republic of Tanzania',
  N: 'United States',
  CX: 'Uruguay',
  UK: 'Uzbekistan',
  YJ: 'Vanuatu',
  YV: 'Venezuela (Bolivarian Republic of)',
  XV: 'Viet Nam',
  '7O': 'Yemen',
  '9J': 'Zambia',
  Z: 'Zimbabwe*',
  A3: 'Bhutan',
  A4: 'Afghanistan',
  A6: 'United Arab Emirates',
  A9: 'Pakistan',
  E: 'Spain',
  H: 'Switzerland',
  J: 'Japan',
  K: 'South Korea',
  L: 'Norway',
  OT: 'Qatar (Military)',
  P5: 'North Korea',
  PL: 'Palau',
  RF: 'Russia (Military)',
  S: 'Sweden',
  T: 'Hungary',
  TC: 'Canada (Transport)',
  UR: 'Ukraine (Former use; deprecated)',
  V: 'Austria',
  VI: 'India',
  VU: 'Laos',
  VV: 'Vietnam',
  XD: 'Mexico',
  XE: 'Mexico',
  XF: 'Mexico',
  XG: 'Mexico',
  XH: 'Mexico',
  XI: 'Mexico',
  XJ: 'Mexico',
  XK: 'Mexico',
  XL: 'Mexico',
  XM: 'Mexico',
  XN: 'Mexico',
  XO: 'Mexico',
  XP: 'Mexico',
  XQ: 'Mexico',
  XR: 'Mexico',
  XS: 'Mexico',
  XW: 'Mexico',
  Y: 'Australia',
  ZB: 'Indonesia',
  ZC: 'Indonesia',
  ZD: 'Indonesia',
  ZF: 'Indonesia',
  ZW: 'China',
  ZY: 'China',
};

// export const airplane =
